# Deep Learning in Medicine
### BMSC-GA 4493, BMIN-GA 3007 
### Lab 2: PyTorch Tutorial and Loss Functions


### Goal of this lab: 
    - Understand Pytorch Tensor, Variables, and AutoGrad. 
    - Understand Loss Functions

### What is PyTorch?
It's a Python based scientific computing package targeted as:
* A replacement for numpy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed

### Tensor
It is similar to Numpy Ndarray
<a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html 


In [1]:
from __future__ import print_function
import torch


#### Tensor Initialization

In [7]:
x = torch.Tensor(6, 2)  # construct a 6x2 matrix, uninitialized


In [8]:
x, x.size()

(
  0.0000 -2.0000
  0.0000 -2.0000
  0.0000  0.0000
  0.0000  0.0000
  0.0000 -2.0000
  0.0000  0.0000
 [torch.FloatTensor of size 6x2], torch.Size([6, 2]))

In [9]:
y = torch.rand(6, 2)  # construct a randomly initialized matrix


In [11]:
y, y.size()

(
  0.4406  0.6783
  0.1337  0.0619
  0.6875  0.6029
  0.8741  0.1559
  0.7339  0.1633
  0.3193  0.2740
 [torch.FloatTensor of size 6x2], torch.Size([6, 2]))

In [13]:
z = torch.ones(7) # construct a matrix of ones


In [7]:
z, z.size()

(
  1
  1
  1
  1
  1
  1
  1
 [torch.FloatTensor of size 7], torch.Size([7]))

#### Operation Example: Addtion
Related reading and reference:
    
* PyTorch documentation:
<a href="http://pytorch.org/docs/0.3.0/"> http://pytorch.org/docs/0.3.0/ </a>


In [14]:
# addition: syntax 1
x + y


 0.4406 -1.3217
 0.1337 -1.9381
 0.6875  0.6029
 0.8741  0.1559
 0.7339 -1.8367
 0.3193  0.2740
[torch.FloatTensor of size 6x2]

In [15]:
# addition: syntax 2
torch.add(x, y)


 0.4406 -1.3217
 0.1337 -1.9381
 0.6875  0.6029
 0.8741  0.1559
 0.7339 -1.8367
 0.3193  0.2740
[torch.FloatTensor of size 6x2]

In [16]:
# addition: giving an output tensor
result = torch.Tensor(6, 2)
torch.add(x, y, out=result)


 0.4406 -1.3217
 0.1337 -1.9381
 0.6875  0.6029
 0.8741  0.1559
 0.7339 -1.8367
 0.3193  0.2740
[torch.FloatTensor of size 6x2]

In [23]:
# addition: in-place
y.add_(x) # adds x to y


  0.4406 -13.3217
  0.1337 -13.9381
  0.6875   0.6029
  0.8741   0.1559
  0.7339 -13.8367
  0.3193   0.2740
[torch.FloatTensor of size 6x2]

#### Numpy Bridge:
The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

##### Convert Torch Tensor to Numpy

In [24]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [25]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [28]:
a.add_(1) # Remember this is an inplace addition
print(a)
print(b) # see how the numpy array changed in value


 4
 4
 4
 4
 4
[torch.FloatTensor of size 5]

[ 4.  4.  4.  4.  4.]


##### Converting Numpy Array to Torch Tensor

In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



####  Used of CUDA

In [38]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y
torch.cuda.is_available()

False

### Autograd: automatic differentiation
* The autograd package provides automatic differentiation for all operations on Tensors.It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

### Variable
* autograd.Variable is the central class of the package. It wraps a Tensor, and supports nearly all of operations defined on it. 
* .backward() computes all the gradients automatically; for non-scalar variable, grad_output argument is the tensor of matching shape
* .data attribute accesses the raw tensor
* .grad access the gradient

### Function
* Variable and Function are interconnected and build up an acyclic graph , that econdes the history of computation. 
* Each variable has a .grad_fn attribute to reference a function created the Variable, expectr the Variables created by the user ( grad_fn = None)

Related Reading and Reference:
<a href="http://pytorch.org/docs/autograd"> http://pytorch.org/docs/autograd </a>

In [70]:
import torch
from torch.autograd import Variable

In [71]:
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [72]:
y = x + 2
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [73]:
print(y.grad_fn)
y.grad_fn

In [74]:
z = y * y * 2
out = z.mean()
print(z, out)

Variable containing:
 18  18
 18  18
[torch.FloatTensor of size 2x2]
 Variable containing:
 18
[torch.FloatTensor of size 1]



In [75]:
# What's the gradient of X before backward() is performed?
print(x.grad)

None


In [83]:
# What's the correct gradient of X?
out.backward(retain_graph=True)
print(x.grad)
x.grad.data.zero_()
# Question: How do we get these values?

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]




 0  0
 0  0
[torch.FloatTensor of size 2x2]

### Loss Functions

 Related Reference: 
<a href="http://pytorch.org/docs/master/nn.html#loss-functions">http://pytorch.org/docs/master/nn.html#loss-functions </a>

#### Mean Square Error
Question: What is mean square error? What are the inputs? What's the output?

In [85]:
import torch.nn as nn
input = Variable(torch.randn(4, 5), requires_grad=True)
target = Variable(torch.randn(4, 5))

In [88]:
print(input)
print(target)

Variable containing:
-0.5224 -0.2094 -0.4130 -1.2632  0.4698
-0.3807 -0.5751  0.2002  0.4548  0.9314
-0.3448 -1.7007 -0.5485  1.5710 -1.3042
-0.7258 -0.9187  0.5458  0.4069  0.9307
[torch.FloatTensor of size 4x5]

Variable containing:
 1.0227  0.6584  0.5919  0.8200 -1.2096
 0.2975 -1.0410 -0.8068 -1.0887  0.7279
-1.1469  0.5255 -0.5370 -0.4546  0.7762
 1.4425  0.7706  0.6710 -0.5637  0.9619
[torch.FloatTensor of size 4x5]



In [26]:
loss = nn.MSELoss()
output = loss(input, target)
output.backward()

In [27]:
output, input

(Variable containing:
  2.4223
 [torch.FloatTensor of size 1], Variable containing:
 -0.7164  0.0381  0.4473 -1.6088 -0.3169
  2.3842 -0.0756 -0.0147  1.2243 -0.4108
  1.0380  2.1929 -0.1660  0.8097 -1.4587
  0.0109  0.5618  0.3386  1.8718  0.1894
 [torch.FloatTensor of size 4x5])

#### Cross Entropy Loss
Question: What is cross entropy loss? What are the inputs? What's the output?

In [28]:
input = Variable(torch.randn(4, 5), requires_grad=True)
target = Variable(torch.LongTensor(4).random_(5))
print(input)
print(target)

Variable containing:
-0.2317 -0.3896 -1.2517 -0.3120 -2.0058
-0.6523  0.1166 -0.7225 -1.0414  1.5915
-1.2071 -2.7916  0.9453 -1.1148 -0.0141
-0.0776 -1.0853  0.3246  0.6947 -2.3474
[torch.FloatTensor of size 4x5]

Variable containing:
 2
 3
 1
 0
[torch.LongTensor of size 4]



In [29]:
# Filling in the code to calculated the cross-entropy loss


### Reference:
* Deep Learning with PyTorch: A 60 Minute Blitz:
    <a href="http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html">http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
    
    
* PyTorch documentation:
<a href="http://pytorch.org/docs/0.3.0/"> http://pytorch.org/docs/0.3.0/ </a>